# Generated by Django 3.0.1 on 2022-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('publishing_date_time', models.DateTimeField()),
                ('thumbnails_urls', models.CharField(max_length=255)),
            ],
        ),
    ]
